services:
  strfry-nostr-relay:
    build: .
    image: ${DOCKER_NAME}:${VERSION}
    container_name: nostr-relay
    volumes:
      - ./strfry.conf:/etc/strfry.conf
      - ./strfry-db:/app/strfry-db
    ports:
      - "7777:7777"
    restart: unless-stopped
  strfry-nostr-community-relay:
    build: .
    image: ${DOCKER_NAME}:${VERSION}
    container_name: community-relay
    volumes:
      - ./strfry.conf:/etc/strfry.conf
      - ./strfry-db-community:/app/strfry-db
    ports:
      - "7778:7777"
    restart: unless-stopped
