services:
  strfry-nostr-relay:
    image: strfry-nostr-relay
    build: .
    volumes:
      - ./strfry.conf:/etc/strfry.conf
      - ./strfry-db:/app/strfry-db
    ports:
      - "7777:7777"
    restart: unless-stopped